In [ ]:
# Function to Check for Zero Values in a Numpy Array
import numpy as np

def has_zero_values(arr):
    # Check if there are any zero values in the array
    return np.any(arr == 0)

# Example usage:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([1, 2, 0, 4, 5])

print(has_zero_values(arr1))  # Output: False
print(has_zero_values(arr2))  # Output: True


False
True


In [ ]:
# Finding Median and Mean of Passing Marks
import numpy as np

def calculate_stats(marks):
    passing_marks = marks[marks >= 40]  # Filter passing marks
    median = np.median(passing_marks)
    mean = np.mean(passing_marks)
    return median, mean

# Example usage:
marks = np.array([35, 45, 50, 30, 60, 55, 40])
median, mean = calculate_stats(marks)
print("Median of passing marks:", median)
print("Mean of passing marks:", mean)


Median of passing marks: 50.0
Mean of passing marks: 50.0


In [ ]:
# Finding Age and Labeling Students
import numpy as np

def label_age(dob):
    today = np.datetime64('now')
    ages = (today - dob).astype('timedelta64[Y]')  # Calculate ages in years

    # Convert ages to integers before comparison
    ages_int = ages.astype(int)

    labels = np.select(
        [ages_int == 18, ages_int == 19, ages_int == 20, ages_int == 21],
        ['First', 'Second', 'Third', 'Fourth'],
        default='Other'
    )

    return ages, labels

# Example usage:
dob = np.array(['2000-01-01', '2001-03-15', '1999-11-20'], dtype='datetime64')
ages, labels = label_age(dob)
for i in range(len(dob)):
    print(f"DOB: {dob[i]}, Age: {ages[i]}, Label: {labels[i]}")

DOB: 2000-01-01, Age: 25 years, Label: Other
DOB: 2001-03-15, Age: 23 years, Label: Other
DOB: 1999-11-20, Age: 25 years, Label: Other


In [ ]:
# Sorting 2D Array by a Column
import numpy as np

def sort_2d_array(arr, column):
    return arr[arr[:, column].argsort()]

# Example usage:
arr = np.array([[3, 1, 2], [5, 2, 1], [1, 3, 3]])
sorted_arr = sort_2d_array(arr, 1)
print("Sorted array by column 1:")
print(sorted_arr)


Sorted array by column 1:
[[3 1 2]
 [5 2 1]
 [1 3 3]]
