In [ ]:
import numpy as np
def one_hot_encode(arr):
  unique_values = np.unique(arr)

  # Create a dictionary mapping unique values to indices.
  value_to_index = {value: index for index, value in enumerate(unique_values)}

  # Create the one-hot encoded array.
  encoded_arr = np.zeros((len(arr), len(unique_values)))
  for i, value in enumerate(arr):
    encoded_arr[i, value_to_index[value]] = 1

  return encoded_arr

# Example usage
arr = np.array([2, 3, 2, 2, 2, 1])
encoded_arr = one_hot_encode(arr)
print(encoded_arr)

[[0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, np.nan, 5, 6, 7, np.nan])
arr = arr[~np.isnan(arr)]
print(arr)

[1. 2. 3. 5. 6. 7.]


In [ ]:
import numpy as np
from scipy.signal import argrelextrema

a = np.array([1, 3, 7, 1, 2, 6, 0, 1])
# Find indices of local maxima
max_ind = argrelextrema(a, np.greater)

# Print the indices
print(max_ind[0])

[2 5]


In [ ]:
import numpy as np

def rolling_window(arr, window, stride):
    """Generates a 2D matrix from a 1D array using strides.

    Args:
        arr: The 1D input array.
        window: The window length.
        stride: The stride length.

    Returns:
        The 2D matrix.
    """
    shape = (int((arr.size - window) / stride + 1), window)
    strides = (arr.itemsize * stride, arr.itemsize)
    return np.lib.stride_tricks.as_strided(arr, shape=shape, strides=strides)

def moving_average(arr, window, stride):
    """Calculates the moving average of a 1D array.

    Args:
        arr: The 1D input array.
        window: The window length.
        stride: The stride length.

    Returns:
        The moving average array.
    """
    matrix = rolling_window(arr, window, stride)
    return np.mean(matrix, axis=1)

# Example usage
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])
window = 4
stride = 2

matrix = rolling_window(arr, window, stride)
print("2D Matrix:")
print(matrix)

moving_avg = moving_average(arr, window, stride)
print("\nMoving Average:")
print(moving_avg)

2D Matrix:
[[ 0  1  2  3]
 [ 2  3  4  5]
 [ 4  5  6  7]
 [ 6  7  8  9]
 [ 8  9 10 11]
 [10 11 12 13]]

Moving Average:
[ 1.5  3.5  5.5  7.5  9.5 11.5]
